name: timezone_contacts
description: A new Flutter project.

publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  timezone: ^0.9.1
  flutter_native_timezone: ^2.0.0
  intl: ^0.17.0
  shared_preferences: ^2.0.17
  provider: ^6.0.5
  sqflite: ^2.2.3
  path_provider: ^2.0.12
  flutter_form_builder: ^7.7.0
  sqlbrite: ^2.6.0
  flutter_slidable: ^2.0.0
  image_picker: ^0.8.6+1
  flutter_svg: ^1.1.6
  package_info_plus: ^3.0.2
  package_info: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/